export let flex = rule`display: flex; position: relative;`;
export const wevenly = rule`justify-content: space-between`;
export const hcenter = rule`align-items: center`;
export const wcenter = rule`justify-content: center`;
export const col = rule`flex-direction: column`;
export const h100 = rule`height:100%`;
export const w100 = rule`width:100%`;
export const clip = rule`overflow: hidden`;
export const scrolly = rule`overflow-y: scroll`;
export const borderbox = rule`box-sizing: border-box`
export const gap = rule`gap: 1em`
export const padding = rule`padding: 1em`
export const inlineflex = rule`display: inline-flex`
